### ISSUE TITLE
Can't login with account

### ISSUE THREAD

**Issue by VincentGreffe** [evolgeniusteam/EvolviewDocumentation#10]
Dear, 

I've used Evolview for a while now, and enjoyed it very much so far. 
I wanted to use it again now, but I can't seem to login in. Are the servers down?
When I try to retrieve my password by using 'forgot password', they say it can't connect to the server.

To be honest, I'm not completely sure I'm using the correct password since it has been a while, but I already tried every possibility. 

Kind regards,

Vincent

**Comment by evolgeniusteam** [comment]
Can you email me from your registered email? I will reset your password manually.Cheers 发自我的iPhone------------------ Original ------------------From: VincentGreffe  <notifications@github.com>Date: Thu,Nov 22,2018 7:39 PMTo: evolgeniusteam/EvolviewDocumentation <EvolviewDocumentation@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [evolgeniusteam/EvolviewDocumentation] Can't login with account (#10)Dear,
I've used Evolview for a while now, and enjoyed it very much so far.
I wanted to use it again now, but I can't seem to login in. Are the servers down?
When I try to retrieve my password by using 'forgot password', they say it can't connect to the server.
To be honest, I'm not completely sure I'm using the correct password since it has been a while, but I already tried every possibility.
Kind regards,
Vincent

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/evolgeniusteam/EvolviewDocumentation","title":"evolgeniusteam/EvolviewDocumentation","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/evolgeniusteam/EvolviewDocumentation"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Can't login with account (#10)"}],"action":{"name":"View Issue","url":"https://github.com/evolgeniusteam/EvolviewDocumentation/issues/10"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/evolgeniusteam/EvolviewDocumentation/issues/10",
"url": "https://github.com/evolgeniusteam/EvolviewDocumentation/issues/10",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Can't login with account (#10)",
"sections": [
{
"text": "",
"activityTitle": "**VincentGreffe**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@VincentGreffe",
"facts": [
{
"name": "Repository: ",
"value": "evolgeniusteam/EvolviewDocumentation"
},
{
"name": "Issue #: ",
"value": 10
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"evolgeniusteam/EvolviewDocumentation\",\n\"issueId\": 10,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"evolgeniusteam/EvolviewDocumentation\",\n\"issueId\": 10\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/evolgeniusteam/EvolviewDocumentation/issues/10"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 415021514\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by VincentGreffe** [comment]
Thank you!
The email adress should either be vincentgreffe@outlook.com or vincent.greffe@student.kuleuven.be but since I can't see on which email I got the account I'm not sure. 
If not, let me know. 

Kind regards,

Vincent

**Comment by evolgeniusteam** [comment]
I have sent your new password to your outlook email.Cheers发自我的iPhone------------------ Original ------------------From: VincentGreffe  <notifications@github.com>Date: Thu,Nov 22,2018 10:17 PMTo: evolgeniusteam/EvolviewDocumentation <EvolviewDocumentation@noreply.github.com>Cc: evolgeniusteam <evolgenius.team@gmail.com>, Comment <comment@noreply.github.com>Subject: Re: [evolgeniusteam/EvolviewDocumentation] Can't login with account(#10)Thank you!
The email adress should either be vincentgreffe@outlook.com or vincent.greffe@student.kuleuven.be but since I can't see on which email I got the account I'm not sure.
If not, let me know.
Kind regards,
Vincent

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/evolgeniusteam/EvolviewDocumentation","title":"evolgeniusteam/EvolviewDocumentation","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/evolgeniusteam/EvolviewDocumentation"}},"updates":{"snippets":[{"icon":"PERSON","message":"@VincentGreffe in #10: Thank you!\r\nThe email adress should either be vincentgreffe@outlook.com or vincent.greffe@student.kuleuven.be but since I can't see on which email I got the account I'm not sure. \r\nIf not, let me know. \r\n\r\nKind regards,\r\n\r\nVincent"}],"action":{"name":"View Issue","url":"https://github.com/evolgeniusteam/EvolviewDocumentation/issues/10#issuecomment-441043653"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/evolgeniusteam/EvolviewDocumentation/issues/10#issuecomment-441043653",
"url": "https://github.com/evolgeniusteam/EvolviewDocumentation/issues/10#issuecomment-441043653",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [evolgeniusteam/EvolviewDocumentation] Can't login with account (#10)",
"sections": [
{
"text": "",
"activityTitle": "**VincentGreffe**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@VincentGreffe",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"evolgeniusteam/EvolviewDocumentation\",\n\"issueId\": 10,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"evolgeniusteam/EvolviewDocumentation\",\n\"issueId\": 10\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/evolgeniusteam/EvolviewDocumentation/issues/10#issuecomment-441043653"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 415021514\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by VincentGreffe** [comment]
Dear, 

Excuse me to bother you again, but I'm have the same problem as before.
Is it possible to reset the password again (vincentgreffe@outlook.com)?

Kind regards,

Vincent
