### ISSUE TITLE
Can't login with account

### ISSUE THREAD

**Issue by ludingdang** [evolgeniusteam/EvolviewDocumentation#14]
Dear,

I've used Evolview for a while now, and enjoyed it very much so far.
I wanted to use it again now, but I can't seem to login in. Are the servers down?
When I try to retrieve my password by using 'forgot password', they say it can't connect to the server.
my email address is luzhiweihn@126.com, looking forward to your reply.

Kind regards,

zhiwei

**Comment by evolgeniusteam** [comment]
Hi,
We are sorry for the inconvenience caused. The site has been upgraded to use more secure HTTPS protocol, so sometimes due to uncleared browser cache, such issues occur.  I have sent you the email with instructions on password reset, kindly let us know if your issues have been resolved.
Regards,
Evolview Team.
