### ISSUE TITLE
download project

### ISSUE THREAD

**Issue by aspitaleri** [evolgeniusteam/EvolviewDocumentation#18]
Hi there,
is it possible to download the whole project (with the annotations), not just nexus/newick/svg file?
Best

**Comment by evolgeniusteam** [comment]
Currently it is not possible. I will ask my phd student to implement this and let you know when it’s done.Cheers发自我的iPhone------------------ Original ------------------From: Andrea Spitaleri  <notifications@github.com>Date: Mon,Oct 21,2019 8:49 PMTo: evolgeniusteam/EvolviewDocumentation <EvolviewDocumentation@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [evolgeniusteam/EvolviewDocumentation] download project (#18)Hi there,
is it possible to download the whole project (with the annotations), not just nexus/newick/svg file?
Best

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/evolgeniusteam/EvolviewDocumentation/issues/18?email_source=notifications\u0026email_token=ADCZDPNF6T4IOSRORUCNDXTQPWQONA5CNFSM4JC42IVKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HTFCSVA",
"url": "https://github.com/evolgeniusteam/EvolviewDocumentation/issues/18?email_source=notifications\u0026email_token=ADCZDPNF6T4IOSRORUCNDXTQPWQONA5CNFSM4JC42IVKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HTFCSVA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by balaram26** [comment]
Hi, I just uploaded the test version with project download feature. you can try it, it downloads the whole project files including the tree and annotation files preserving the file names and folder structure. at present you can download them as zip from project management window. i Have attached the screenshot of the project management window showing the project zip download icon. Here is the link for the test version, click here `https://www.evolgenius.info/evolview-test/#login`
![Screen Shot 2019-11-05 at 10 52 02 AM](https://user-images.githubusercontent.com/1926881/68175501-6da56080-ffbc-11e9-8dc1-0eec9bd65b3b.png)

Hope this helps!!

**Comment by aspitaleri** [comment]
great!! I will test it and let you know in case of issues.
Thanks!

**Comment by balaram26** [comment]
Hi could you confirm it again?  if you still have the link issues? sorry as i checked the link and it is active, here it is : [https://evolgenius.info//evolview-test/#login](https://evolgenius.info//evolview-test/#login)

**Comment by aspitaleri** [comment]
Hi @balaram26 thanks for your reply and help. Yes now it works. It takes few seconds to load the page. It recognized my login and my projects. Also download are there.
Thanks for now!
