### ISSUE TITLE
failed to upload my tree file

### ISSUE THREAD

**Issue by liuxiangpei** [evolgeniusteam/EvolviewDocumentation#23]
I can't upload my tree file. The status was  "validating your tree" though I waited for a long time. While when I tested with a tree file in the showcases, it can upload quickly...

**Comment by evolgeniusteam** [comment]
Can you send me the tree file? It could be that your file is too large for the server to parse. I will take a look ASAP.Cheers发自我的iPhone------------------ Original ------------------From: liuxiangpei  <notifications@github.com>Date: Sun,May 24,2020 7:28 PMTo: evolgeniusteam/EvolviewDocumentation <EvolviewDocumentation@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [evolgeniusteam/EvolviewDocumentation] failed to upload my tree file(#23)
I can't upload my tree file. The status was  "validating your tree" though I waited for a long time. While when I tested with a tree file in the showcases, it can upload quickly...

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/evolgeniusteam/EvolviewDocumentation/issues/23",
"url": "https://github.com/evolgeniusteam/EvolviewDocumentation/issues/23",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by liuxiangpei** [comment]
I am wondering whether it's a format problem...because I can create a tree in iTOL, while can't create in evolview and figtree...however I can't figure it out since I don't the principle behind it...I hope you can help me~Thanks a lot  
















At 2020-05-24 19:42:32, "evolgeniusteam" <notifications@github.com> wrote:

Can you send me the tree file? It could be that your file is too large for the server to parse. I will take a look ASAP.Cheers发自我的iPhone------------------ Original ------------------From: liuxiangpei <notifications@github.com>Date: Sun,May 24,2020 7:28 PMTo: evolgeniusteam/EvolviewDocumentation <EvolviewDocumentation@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [evolgeniusteam/EvolviewDocumentation] failed to upload my tree file(#23)
I can't upload my tree file. The status was "validating your tree" though I waited for a long time. While when I tested with a tree file in the showcases, it can upload quickly...

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/evolgeniusteam/EvolviewDocumentation/issues/23",
"url": "https://github.com/evolgeniusteam/EvolviewDocumentation/issues/23",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by evolgeniusteam** [comment]
Can you send me the tree file to evolgenius.team@gmail.com? Or simply copy&paste the tree here.

Cheers

**Comment by evolgeniusteam** [comment]
Dendroscope spotted an error in your tree:
![image](https://user-images.githubusercontent.com/12947901/82772518-f4932b00-9e71-11ea-8ea7-6fc2ab260876.png)

Add a ',' before '(' should fix it.

Cheers
