### ISSUE TITLE
Problem to upload data on macOS 

### ISSUE THREAD

**Issue by Daniherrera77** [evolgeniusteam/EvolviewDocumentation#26]
Hello, 
I have been trying to upload "Group labels" and also "data color shapes" to my tree, but I can't see the submit button :/. I'm using Firefox on macOS catalina which I saw works better than Chrome and Safari.

Finally I could upload the data using Ubuntu , but my tree is not saved as a project, so I couldn't access again from my account on mac.

**Thanks for the new version of the server is really useful!**

**Comment by evolgeniusteam** [comment]
See the screenshot below, I am using Chrome on Mac:

![image](https://user-images.githubusercontent.com/12947901/88353705-1b49e100-cd91-11ea-823d-57a3986ef039.png)

The "data color shapes" button is the next button.

I do not have a Linux desktop at hand. please give it a try and let me know if the issue is not solved.

**Comment by balaram26** [comment]
Hi @Daniherrera77 i am closing this issue as it’s been inactive for long time. Hope your issue has been solved based on the response of our evolview team. Kindly let us know if you have further issues.
