### ISSUE TITLE
Cannot access account

### ISSUE THREAD

**Issue by VincentGreffe** [evolgeniusteam/EvolviewDocumentation#32]
Dear,

I'm unable to login into my account (if I say I forgot my password it cannot access the server).
I faced this problem before, and then it was needed to reset my password.
Is it possible to do this again (vincentgreffe@outlook.com)?

Kind regards,

Vincent

**Comment by sharmin-mim** [comment]
Dear, 
I am facing same problem. I can't access my account. I think the function of "retrieving password" is broken. When I try EvolView version 3, I also can't access that page. Screenshot of this problem is attached.
![image](https://user-images.githubusercontent.com/60011513/157166772-0c2b1058-dcfb-43d3-a449-0836a8f6efa8.png)

**Comment by balaram26** [comment]
> Dear,
> 
> I'm unable to login into my account (if I say I forgot my password it cannot access the server). I faced this problem before, and then it was needed to reset my password. Is it possible to do this again ([vincentgreffe@outlook.com](mailto:vincentgreffe@outlook.com))?
> 
> Kind regards,
> 
> Vincent

Hi vincent, We are sorry for the issues caused. I have checked your account and found your password has been updated after our reset mail. So i have sent new email with password reset instructions. Kindly let us know if you still have issues using the account.

With regards,
Evolgenius Team

**Comment by balaram26** [comment]
> Dear, I am facing same problem. I can't access my account. I think the function of "retrieving password" is broken. When I try EvolView version 3, I also can't access that page. Screenshot of this problem is attached. ![image](https://user-images.githubusercontent.com/60011513/157166772-0c2b1058-dcfb-43d3-a449-0836a8f6efa8.png)

Hi sharmin-mim,

We have received your mail regarding the login request. I have sent an email with login reset instructions. Kindly let us know if you face any other issues.  We are sorry for the issues caused by the version 3 website address. Here is the working link : https://evolgenius.info/evolview-v3/ , which was tested and online during the time of positing the message.

Kindly let us know if you still have issues using the account.

With regards,
Evolgenius Team

**Comment by sharmin-mim** [comment]
Evolgenius Team,
Thanks. The problem is solved.

With regards,
sharmin-mim
